### ISSUE TITLE
profileCC breaks when there is no rating for a user in a specific chess category like bullet

### ISSUE THREAD

**Issue by cnunezre** [jalpp/Chesslise#64]
**Describe the bug**
profileCC breaks when there is no rating for a user in a specific chess category like bullet

**To Reproduce**
1. /profilecc cnunezre

**Expected behavior**
I would expect to show the category with a default value of zero, empty or ? like in the  lichess command /profile. 

**Screenshots**
<img width="948" alt="Screenshot 2024-06-19 at 4 00 25 PM" src="https://github.com/jalpp/Chesslise/assets/1489384/c35eacce-5d10-4f70-8737-64576322923b">

Exception when testing locally
`2024-06-19 15:56:24 [JDA] [ERROR] One of the EventListeners had an uncaught exception
java.lang.NullPointerException: Cannot invoke "io.github.sornerol.chess.pubapi.domain.player.stats.RatingPoolStats.getLast()" because the return value of "io.github.sornerol.chess.pubapi.domain.player.stats.PlayerStats.getChessBullet()" is null
	at Chesscom.CCProfile.getCCProfile(CCProfile.java:27)
	at Discord.HelperModules.ModalHelperContextModule.handleChessComProfileOnFormSubmit(ModalHelperContextModule.java:114)
	at Discord.HandlerModules.ModalContextModule.handleLogic(ModalContextModule.java:25)
	at Discord.MainHandler.CommandHandler.onModalInteraction(CommandHandler.java:48)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:463)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:169)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:94)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
`

**Comment by jalpp** [comment]
bug is reproduced opening this as good first issue to be fixed if you want @cnunezre you can take over

**Comment by cnunezre** [comment]
I will work on the fix - thanks for the prompt response.
